create_clock -period 20.833 -name cam_pclk [get_ports cam_pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cam_pclk_IBUF]
set_property -dict {PACKAGE_PIN E4 IOSTANDARD LVCMOS18} [get_ports led_init]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS18} [get_ports led_pclk]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS18} [get_ports cam_pclk]
set_property -dict {PACKAGE_PIN H8 IOSTANDARD LVCMOS18} [get_ports cam_vsync]
set_property -dict {PACKAGE_PIN R8 IOSTANDARD LVCMOS18} [get_ports cam_href]
set_property -dict {PACKAGE_PIN J7 IOSTANDARD LVCMOS18} [get_ports {cam_data[0]}]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS18} [get_ports {cam_data[1]}]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS18} [get_ports {cam_data[2]}]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS18} [get_ports {cam_data[3]}]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS18} [get_ports {cam_data[4]}]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS18} [get_ports {cam_data[5]}]
set_property -dict {PACKAGE_PIN L7 IOSTANDARD LVCMOS18} [get_ports {cam_data[6]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS18} [get_ports {cam_data[7]}]
set_property -dict {PACKAGE_PIN K7 IOSTANDARD LVCMOS18} [get_ports cam_pwdn]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS18} [get_ports cam_rst_n]
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVCMOS33 PULLUP true} [get_ports cam_scl]
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS33 PULLUP true} [get_ports cam_sda]
